name: Node.js CI

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm install
        npm run lint

  test:

    name: test with Node.js ${{ matrix.node-version }} on ${{ matrix.runs-on }}

    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        node-version: ['12', '14', '16']
        runs-on: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test
